Repository MastersAcademy/ruby-course-2018, pull requests merged in 2018-11, with the labels that each got.

#8 HW 1 Vlad Metelap
  ruby_basic/vlad.metelap/task1.rb
  ruby_basic/vlad.metelap/task2.rb
  ruby_basic/vlad.metelap/task3.rb
  ruby_basic/vlad.metelap/task4.rb
  ruby_basic/vlad.metelap/task5.rb
  ruby_basic/vlad.metelap/task6.rb
  ruby_basic/vlad.metelap/task7.rb
  ruby_basic/vlad.metelap/task8.rb
Labels: enhancement

#11 Homework #1
  ruby_basic/eugene.tymoshenko/task_1.rb
  ruby_basic/eugene.tymoshenko/task_2.rb
  ruby_basic/eugene.tymoshenko/task_3.rb
  ruby_basic/eugene.tymoshenko/task_4.rb
  ruby_basic/eugene.tymoshenko/task_5.rb
  ruby_basic/eugene.tymoshenko/task_6.rb
  ruby_basic/eugene.tymoshenko/task_7.rb
  ruby_basic/eugene.tymoshenko/task_8.rb
Labels: вимагає змін

#9 Homework#1 almost done
  .gitignore
  ruby_basic/nikolay.braslavets/home_task_1/1.rb
  ruby_basic/nikolay.braslavets/home_task_1/2.rb
  ruby_basic/nikolay.braslavets/home_task_1/3.rb
  ruby_basic/nikolay.braslavets/home_task_1/4.rb
  ruby_basic/nikolay.braslavets/home_task_1/5.rb
  ruby_basic/nikolay.braslavets/home_task_1/6.rb
  ruby_basic/nikolay.braslavets/home_task_1/7.rb
  ruby_basic/nikolay.braslavets/home_task_1/8.rb
  ruby_basic/nikolay.braslavets/home_task_1/example.txt
Labels: завдання відсутнє

#13 Homework ruby basics
  ruby_basic/oleksandr.zaruba/task1.rb
  ruby_basic/oleksandr.zaruba/task2.rb
  ruby_basic/oleksandr.zaruba/task3.rb
  ruby_basic/oleksandr.zaruba/task4.rb
  ruby_basic/oleksandr.zaruba/task5.rb
  ruby_basic/oleksandr.zaruba/task6.rb
  ruby_basic/oleksandr.zaruba/task7.rb
  ruby_basic/oleksandr.zaruba/task8.rb
Labels: вимагає змін

#12 homework 1
  ruby_basic/boris.larioshin/some.txt
  ruby_basic/boris.larioshin/task_2.rb
  ruby_basic/boris.larioshin/task_3.rb
  ruby_basic/boris.larioshin/task_4.rb
  ruby_basic/boris.larioshin/task_5.rb
  ruby_basic/boris.larioshin/task_6.rb
  ruby_basic/boris.larioshin/task_7.rb
  ruby_basic/boris.larioshin/task_8.rb
Labels: вимагає змін

#25 Homework 2
  objects/taras.turchenko/.keep
  objects/taras.turchenko/colorized_string.rb
  objects/taras.turchenko/dynamic_math.rb
  objects/taras.turchenko/mario_game.rb
  objects/taras.turchenko/task_1/base_game.rb
  objects/taras.turchenko/task_1/the_witcher.rb
  objects/taras.turchenko/task_2.rb
  objects/taras.turchenko/task_3.rb
  objects/taras.turchenko/task_4.rb
  objects/taras.turchenko/task_5.rb
  objects/taras.turchenko/task_6.rb
  objects/taras.turchenko/task_8/console_io.rb
  objects/taras.turchenko/task_8/mario.rb
Labels: вимагає змін

#14 Частина робіт. Те що не встиг додам завтра
  ruby_basic/victor.skyba/task_3.rb
  ruby_basic/victor.skyba/task_4.rb
  ruby_basic/victor.skyba/task_6.rb
  ruby_basic/victor.skyba/task_7.rb
  ruby_basic/victor.skyba/task_8.rb
Labels: not fixed, вимагає змін

#16 Add 3 tasks hw1
  ruby_basic/ievgen.saiko/Task01.rb
  ruby_basic/ievgen.saiko/Task02.rb
  ruby_basic/ievgen.saiko/Task02_text.txt
  ruby_basic/ievgen.saiko/Task03.rb
  ruby_basic/ievgen.saiko/TimeZones.json
Labels: not fixed, вимагає змін

#23 Homework #2
  objects/eugene.tymoshenko/game_actions.rb
  objects/eugene.tymoshenko/math_operations.rb
  objects/eugene.tymoshenko/task_1.rb
  objects/eugene.tymoshenko/task_2.rb
  objects/eugene.tymoshenko/task_3.rb
  objects/eugene.tymoshenko/task_4.rb
  objects/eugene.tymoshenko/task_5.rb
  objects/eugene.tymoshenko/task_6.rb
  objects/eugene.tymoshenko/task_7.rb
Labels: вимагає змін

#20 Homework2
  objects/eugene.doroshenko/games_methods.rb
  objects/eugene.doroshenko/mario_game.rb
  objects/eugene.doroshenko/tanks_game.rb
  objects/eugene.doroshenko/task3.rb
Labels: вимагає змін

#18 Homework_2
  objects/vlad.vovk/01_task.rb
  objects/vlad.vovk/02_task.rb
  objects/vlad.vovk/03_task.rb
  objects/vlad.vovk/04_task.rb
  objects/vlad.vovk/05_task.rb
  objects/vlad.vovk/06_task.rb
  objects/vlad.vovk/colorize.rb
  objects/vlad.vovk/game_constructor.rb
Labels: вимагає змін

#17 Home Work #2
  objects/vazgen.bakhchagulian/mario_game.rb
  objects/vazgen.bakhchagulian/task3.rb
  objects/vazgen.bakhchagulian/task4+6.rb
  objects/vazgen.bakhchagulian/task5.rb
  objects/vazgen.bakhchagulian/task7.rb
Labels: вимагає змін

#29 homework 2
  objects/boris.larioshin/base_game.rb
  objects/boris.larioshin/colored_line.rb
  objects/boris.larioshin/task_1.rb
  objects/boris.larioshin/task_2.rb
  objects/boris.larioshin/task_3.rb
  objects/boris.larioshin/task_4.rb
  objects/boris.larioshin/task_5.rb
  objects/boris.larioshin/task_6.rb
  objects/boris.larioshin/task_7.rb
Labels: вимагає змін

#31 Homework2 Tasks 4, 5 and 6
  objects/eugene.doroshenko/colors.rb
  objects/eugene.doroshenko/math_operations_list.rb
  objects/eugene.doroshenko/task4_6.rb
  objects/eugene.doroshenko/task5.rb
Labels: вимагає змін

#30 Changes +task 5 and 1
  ruby_basic/victor.skyba/file
  ruby_basic/victor.skyba/run
  ruby_basic/victor.skyba/task_1.rb
  ruby_basic/victor.skyba/task_2.rb
  ruby_basic/victor.skyba/task_3.rb
  ruby_basic/victor.skyba/task_4.rb
  ruby_basic/victor.skyba/task_5.rb
  ruby_basic/victor.skyba/task_6.rb
  ruby_basic/victor.skyba/task_7.rb
  ruby_basic/victor.skyba/task_8.rb
Labels: вимагає змін
